# Generated by Django 2.1.5 on 2019-03-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_detials_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myuname', models.CharField(max_length=20)),
                ('foll_uname', models.CharField(max_length=30)),
                ('foll_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user_detials')),
                ('myid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user_detials')),
            ],
        ),
        migrations.CreateModel(
            name='followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myusname', models.CharField(max_length=20)),
                ('follw_uname', models.CharField(max_length=30)),
                ('follw_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user_detials')),
                ('myuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user_detials')),
            ],
        ),
    ]
