# Generated by Django 2.1.5 on 2019-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=52)),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('propic', models.CharField(max_length=100)),
                ('followings', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
