# Generated by Django 2.1.5 on 2019-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detials',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
