# Generated by Django 2.1.5 on 2019-03-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_detials_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detials',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
