# Generated by Django 2.1.5 on 2019-03-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_detials_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detials',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
