# Generated by Django 2.1.5 on 2019-03-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
