# Generated by Django 2.1.5 on 2019-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
