# Generated by Django 2.1.5 on 2019-03-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imguploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100, unique=True)),
                ('caption', models.CharField(max_length=70)),
                ('likes', models.IntegerField()),
                ('command', models.IntegerField()),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_detials')),
            ],
        ),
    ]
