# Generated by Django 2.1.5 on 2019-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imguploads',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
